const fs = require('fs');
// [name, icon, desc, url, tag]
const D = {
  variants: [
    ['OpenClaw官方','🦞','开源本地优先AI助手','https://openclaw.ai','local'],
    ['Kimi Claw','🌙','集成OpenClaw的Kimi云端版','https://www.kimi.com/bot','cloud'],
    ['MaxClaw','⚡','10秒完成OpenClaw云端部署','https://agent.minimaxi.com/max-claw','cloud'],
    ['飞书OpenClaw','📋','原版OpenClaw+飞书官方插件','https://openclaw.feishu.cn/home','cloud'],
    ['ArkClaw','🌋','火山引擎OpenClaw云端版','https://www.volcengine.com/experience/ark?mode=claw','cloud'],
    ['扣子Coze','🤖','字节旗下AI Agent开发平台','https://code.coze.cn/home','cloud'],
    ['DuClaw','🐾','百度即开即用OpenClaw智能体','https://cloud.baidu.com/product/duclaw.html','cloud'],
    ['MiMo Claw','📱','小米大模型驱动OpenClaw智能体','https://aistudio.xiaomimimo.com/','cloud'],
    ['StepClaw','🚀','阶跃星辰云端AI助手','https://www.stepfun.com/openclaw','cloud'],
    ['AstronClaw','🌟','科大讯飞一键部署OpenClaw','https://agent.xfyun.cn/astron-claw','cloud'],
    ['Happycapy','🦦','云端Agent原生计算机','https://happycapy.ai/','cloud'],
    ['Qclaw','💬','腾讯本地版支持微信直联','https://claw.guanjia.qq.com/','local'],
    ['DuMate','🖥️','百度桌面AI智能体办公搭子','https://cloud.baidu.com/product/dumate.html','local'],
    ['LobsterAI','🦞','有道龙虾全场景个人助理','https://lobsterai.youdao.com/','local'],
    ['WorkBuddy','💼','AI原生桌面智能体工作台','https://www.codebuddy.cn/work/','local'],
    ['AutoClaw','🧠','智谱含AutoGLM浏览器自动化','https://autoglm.zhipuai.cn/autoclaw/','local'],
    ['悟空','🐵','阿里企业级AI工作平台钉钉接入','https://www.dingtalk.com/wukong','local'],
    ['360安全龙虾','🔒','安全模式为核心的OpenClaw','https://claw.360.cn/','local'],
    ['EasyClaw','⚙️','一键部署+可视化技能配置','https://easyclaw.com/zh-cn/','local'],
    ['CoPaw','🐾','阿里云协同智能体工作台','https://copaw.agentscope.io/','local'],
    ['JVS Claw','☁️','阿里云多Agent协作平台','https://jvs.wuying.aliyun.com/','cloud'],
    ['Tabbit','🐰','浏览器插件+Agent自动执行','https://tabbitbrowser.com/','local'],
    ['Manus','🤲','全流程自动化Agent','https://manus.im/','cloud'],
    ['牛马AI','🐂','本地免费版Manus','https://niuma.ai/','free'],
    ['QoderWork','📝','自然语言完成文件数据处理','https://qoder.com/qoderwork','local'],
    ['阶跃桌面伙伴','🖥️','会主动做事的桌面Agent','https://www.stepfun.com/download','local'],
    ['Claude Code','🤖','Anthropic终端AI编程Agent','https://claude.ai/code','cloud'],
    ['OpenCode','💻','开源终端AI编程助手','https://opencode.ai/','free'],
    ['Codex CLI','⌨️','OpenAI本地编程Agent','https://github.com/openai/codex','free'],
    ['Gemini CLI','💎','Google终端Gemini Agent','https://github.com/google-gemini/gemini-cli','free'],
  ],
  cloud: [
    ['Railway','🚂','极简云部署支持一键OpenClaw','https://railway.app','cloud'],
    ['Zeabur','🌊','对中国友好的现代部署平台','https://zeabur.com','cloud'],
    ['Render','🎨','免费额度友好全栈云平台','https://render.com','cloud'],
    ['Fly.io','✈️','边缘计算平台全球节点','https://fly.io','cloud'],
    ['阿里云ECS','🟠','国内主流云服务器稳定可靠','https://www.aliyun.com/product/ecs','cloud'],
    ['腾讯云CVM','🔵','腾讯云服务器国内速度快','https://cloud.tencent.com/product/cvm','cloud'],
    ['华为云ECS','🌺','华为云弹性云服务器','https://www.huaweicloud.com/product/ecs.html','cloud'],
    ['百度智能云','🐻','百度云服务器适合AI应用','https://cloud.baidu.com/product/bcc.html','cloud'],
    ['七牛云','🐂','对象存储+计算静态资源优选','https://www.qiniu.com','cloud'],
    ['AWS EC2','🟡','全球最大云平台功能最全','https://aws.amazon.com/ec2/','cloud'],
    ['Google Cloud','🌈','Google云与AI服务深度集成','https://cloud.google.com','cloud'],
    ['Azure','🔷','微软云企业级稳定可靠','https://azure.microsoft.com','cloud'],
    ['DigitalOcean','🌊','对开发者友好价格实惠','https://www.digitalocean.com','cloud'],
    ['Vultr','⚡','高性价比全球节点丰富','https://www.vultr.com','cloud'],
    ['Hetzner','🇩🇪','德国云价格极低性能优秀','https://www.hetzner.com','cloud'],
    ['PikaPods','🫛','一键部署开源应用含OpenClaw','https://www.pikapods.com','cloud'],
    ['Coolify','❄️','开源自托管PaaS类Heroku','https://coolify.io','free'],
    ['Elestio','🎯','全托管开源软件部署平台','https://elest.io','cloud'],
    ['Caprover','⚓','免费开源PaaS自部署超简单','https://caprover.com','free'],
    ['Cloudflare','🔥','Workers边缘部署免费额度大','https://www.cloudflare.com','free'],
    ['京东云','🛒','京东云服务器国内稳定','https://www.jdcloud.com','cloud'],
    ['UCloud','🌐','国内优质云出海节点丰富','https://www.ucloud.cn','cloud'],
    ['天翼云','📡','中国电信旗下云服务','https://www.ctyun.cn','cloud'],
    ['移动云','📶','中国移动云计算服务','https://ecloud.10086.cn','cloud'],
    ['金山云','⚔️','金山旗下企业级云服务','https://www.ksyun.com','cloud'],
    ['Linode','🌍','老牌VPS稳定可靠','https://www.linode.com','cloud'],
    ['Vercel','▲','前端优先部署免费额度充足','https://vercel.com','free'],
    ['Dokploy','🚀','开源Docker部署平台','https://dokploy.com','free'],
    ['Northflank','🧭','现代云原生部署平台','https://northflank.com','cloud'],
    ['Porter','🎒','基于Kubernetes简化部署','https://porter.run','cloud'],
  ],
  tutorials: [
    ['OpenClaw官方文档','📖','最权威的OpenClaw使用指南','https://docs.openclaw.ai','free'],
    ['OpenClaw GitHub','🐙','源代码及Issue讨论','https://github.com/openclaw/openclaw','free'],
    ['ClawHub技能市场','🦞','技能发现安装更新一站搞定','https://clawhub.com','free'],
    ['Claw123导航','🧭','OpenClaw中文社区导航站','https://www.claw123.com/','free'],
    ['OpenClaw Discord','💬','官方英文社区实时交流','https://discord.com/invite/clawd','free'],
    ['B站OpenClaw合集','📺','国内最全OpenClaw视频教程','https://search.bilibili.com/all?keyword=OpenClaw','free'],
    ['YouTube教程','▶️','英文视频教程汇总','https://www.youtube.com/results?search_query=OpenClaw','free'],
    ['少数派专题','✍️','少数派OpenClaw使用心得','https://sspai.com/search/post/OpenClaw','free'],
    ['CSDN教程','💻','CSDN技术博客OpenClaw专题','https://so.csdn.net/so/search?q=OpenClaw','free'],
    ['掘金教程','💎','掘金社区OpenClaw文章','https://juejin.cn/search?query=OpenClaw','free'],
    ['知乎专栏','🔍','知乎OpenClaw讨论汇总','https://www.zhihu.com/search?q=OpenClaw','free'],
    ['OpenClaw Docs部署篇','🖥️','从零开始部署OpenClaw','https://docs.openclaw.ai/get-started/install/','free'],
    ['Skills开发指南','🛠️','如何为OpenClaw编写技能','https://docs.openclaw.ai/context/rules','free'],
    ['OpenClaw配置调优','⚙️','高级配置与性能调优','https://docs.openclaw.ai/settings','free'],
